# Generated by Django 5.0.6 on 2024-06-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_placement', models.DateField(verbose_name='Дата')),
                ('num_item', models.CharField(db_index=True, max_length=30, null=True, unique=True, verbose_name='№ УВР')),
                ('num_transport', models.CharField(db_index=True, max_length=255, null=True, verbose_name='№ авто')),
                ('num_doc', models.CharField(blank=True, max_length=255, null=True, verbose_name='№ документов')),
                ('date_docs', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата доков')),
                ('documents', models.CharField(blank=True, max_length=255, null=True, verbose_name='Документы')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус УВР')),
                ('num_nine', models.CharField(blank=True, max_length=30, null=True, verbose_name='№ Длинной "9"')),
                ('num_td', models.CharField(blank=True, max_length=50, null=True, verbose_name='Таможенное разрешение')),
                ('path_doc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ERIPDataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_account', models.CharField(max_length=20, null=True, verbose_name='Счёт договора')),
                ('payer_name', models.CharField(max_length=100, null=True, verbose_name='ФИО плательщика')),
                ('bill_pay', models.FloatField(blank=True, null=True, verbose_name='Сумма оплаты')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('last_read_time', models.DateTimeField(blank=True, null=True, verbose_name='Время последнего чтения')),
            ],
            options={
                'verbose_name': 'ERIP данные',
                'verbose_name_plural': 'ERIP данные',
                'ordering': ['id'],
            },
        ),
    ]
