# Generated by Django 5.0.6 on 2024-06-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_assist', '0002_pdfdatabase_eripdatabase_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eripdatabase',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='documentinfo',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='PDF файл'),
        ),
    ]
