# Generated by Django 5.0.6 on 2024-06-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_assist', '0003_remove_eripdatabase_pdf_file_documentinfo_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentinfo',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='documentinfo',
            name='pdf_blob',
            field=models.BinaryField(blank=True, null=True, verbose_name='PDF файл'),
        ),
    ]
