# Generated by Django 5.0.6 on 2024-07-31 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_assist', '0004_remove_documentinfo_pdf_file_documentinfo_pdf_blob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentinfo',
            name='path_doc',
        ),
        migrations.RemoveField(
            model_name='documentinfo',
            name='pdf_blob',
        ),
        migrations.RemoveField(
            model_name='pdfdatabase',
            name='in_use',
        ),
    ]
