# Generated by Django 5.0.6 on 2024-07-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_assist', '0007_alter_pdfdatabase_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdatabase',
            name='doc_number',
            field=models.CharField(max_length=30, unique=True, verbose_name='Номер уведомления'),
        ),
        migrations.AlterField(
            model_name='pdfdatabase',
            name='file_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='pdfdatabase',
            name='status',
            field=models.CharField(blank=True, choices=[('uploaded', 'Загружен'), ('linked', 'Связан'), ('not_found', 'Не найден')], default='uploaded', max_length=20, verbose_name='Статус'),
        ),
    ]
