# Generated by Django 5.0.6 on 2024-08-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_assist', '0009_pdfdatabase_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='pdfdatabase',
            name='status',
            field=models.CharField(blank=True, choices=[('not_found', 'Не найден'), ('linked', 'Связан')], default='not_found', max_length=20, verbose_name='Статус'),
        ),
    ]
